### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by DeadLyBro** [CumcordLoaders/Browser#2]
![Screenshot_1](https://github.com/CumcordLoaders/Browser/assets/31214077/17b1f6fe-fc69-44ab-b888-7862ea760f7e)
You can see the error on screenshot.

**Comment by yellowsink** [comment]
I'm afraid Cumcord is dead, and is no longer maintained or expected to work.

For more info see [here](https://cumcord.com/an-exercise-in-futility).

I suggest you use either [Vencord](https://vencord.dev/), the current largest client mod, or [shelter](https://github.com/uwu/shelter), which is, I guess, Cumcord's spiritual successor.
